apiVersion: v1
kind: ConfigMap
metadata:
  name: bao-dragonfly-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
data:
  DRAGONFLY_HOST: "${DRAGONFLY_HOST}"
  DRAGONFLY_PORT: "${DRAGONFLY_PORT}"

