apiVersion: v1
kind: Service
metadata:
  name: dragonfly-service
  namespace: bao-${DEPLOY_ENV}-env
spec:
  selector:
    app: dragonfly-service
  ports:
    - name: dragonfly
      port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP

