apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: bao-${DEPLOY_ENV}-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-service
  template:
    metadata:
      labels:
        app: postgres-service
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_INITDB_ARGS
              value: "--auth=trust"
          envFrom:
            - configMapRef:
                name: bao-${DEPLOY_ENV}-config
            - secretRef:
                name: bao-${DEPLOY_ENV}-secret
          resources:
            requests:
              cpu: "0.3"
              memory: "512Mi"
            limits:
              cpu: "0.5"
              memory: "1Gi"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool-deployment
  namespace: bao-${DEPLOY_ENV}-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgpool-service
  template:
    metadata:
      labels:
        app: pgpool-service
    spec:
      containers:
        - name: pgpool
          image: bitnami/pgpool:4.5.2
          imagePullPolicy: IfNotPresent
          env:
            - name: PGPOOL_BACKEND_NODES
              valueFrom:
                configMapKeyRef:
                  name: bao-${DEPLOY_ENV}-config
                  key: PGPOOL_BACKEND_NODES
            - name: PGPOOL_ENABLE_POOL_HBA
              value: "yes"
            - name: PGPOOL_ALLOW_CLEAR_TEXT_FRONTEND_AUTH
              value: "yes"
            - name: PGPOOL_LOAD_BALANCE_MODE
              value: "off"
            - name: PGPOOL_CONNECTION_CACHE
              value: "on"
            - name: PGPOOL_POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: bao-${DEPLOY_ENV}-config
                  key: POSTGRES_USER
            - name: PGPOOL_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bao-${DEPLOY_ENV}-secret
                  key: POSTGRES_PASSWORD
            - name: BITNAMI_DEBUG
              value: "true"
          envFrom:
            - configMapRef:
                name: bao-${DEPLOY_ENV}-config
            - secretRef:
                name: bao-${DEPLOY_ENV}-secret
          resources:
            requests:
              cpu: "0.3"
              memory: "256Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"